### ISSUE TITLE
I have been banned on beatleader

### ISSUE THREAD

**Issue by jacmoh** [oli-ctrl/ShortSaber#5]
I was using beat leader and using the mod and score submiton was on and I got banned please contact me on discord it's  TheRealBlueInkJacob#6144

**Comment by oli-ctrl** [comment]
were you on the latest version of the mod??
as score submission should be disabled on the latest if the sabers are made longer

**Comment by oli-ctrl** [comment]
What exactly were you doing when you got banned?
